dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
